# 配置添加
gmodel:
  default:
    dsn: username:password@tcp(host:port)/rencon?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    table: '*'
    pkg: internal   #要生成model所属包名
    with_table: true
    output_path: './dao/internal'  #输出model文件目录
    table_prefix: tbl_
    json_tag: true
    gorm_type: true
    unsigned: false #若为TRUE 则生成 uint类型; FALSE 为 int; default false
  second:
    dsn: teiasd
    table: '*'
    pkg: internal   #要生成model所属包名
    with_table: true
    output_path: './dao/internal'  #输出model文件目录
    table_prefix: tbl_
    json_tag: true
    gorm_type: true
    unsigned: false #若为TRUE 则生成 uint类型; FALSE 为 int; default false